django_blog/blogs/urls.py
from django.urls import path
from .import views

app_name = 'blogs'
urlpatterns = [
        path('', views.index, name='index'),
        path('detail/<int:blog_id>/', views.detail, name='detail'),
        ]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/blogs/models.py
from django.db import models
from stdimage.models import StdImageField


# Create your models here.

class Blog(models.Model):
    title = models.CharField(blank=False, null=False, max_length=150)
    text = models.TextField(blank=True)
    #以下追加
    image = StdImageField(upload_to='blogs', blank=True, null=True, variations={
        'large': (600, 400),
        'thumbnail': (100, 100, True),
        'medium': (300, 200),
        })
    #終わり
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.title

django_blog/blogs/forms.py
from django import forms

class PhotoForm(forms.Form):

    image = forms.ImageField()

django_blog/blogs/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from .models import Blog
from .forms import PhotoForm

def index(request):
    blog_list = Blog.objects.order_by('-created_datetime')
    page = request.GET.get('page',1)

    paginator = Paginator(blog_list,1)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)
    return render(request, 'blogs/index.html', {'blogs': blogs})

    if request.method == 'GET':
        return render(request, 'blogs/index.html', {
                'form': PhotoForm(),
            })

def detail(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    return render(request, 'blogs/detail.html', {'blog':blog})

django_blog/blogs/templates/blogs/detail.html
<!DOCTYPE html>
<html>
<head>
	<title>Blog Apps</title>
</head>
<body>
	<h1 style="text-align: center;">{{ blog.title }}</h1>
	<div style="width: 70%; margin: 0px auto;">
		<div>
			<div style="margin: 60px 20px;">
					{% if blog.image%}
					<p><a href="{{ blog.image.url }}"><img alt="" src="{{ blog.image.large.url }}"/></a></p>
					{% endif %}
				{{ blog.text }}
			</div>
			<div style="text-align: center; margin-top: 50px">
				<a href="{% url 'blogs:index'%}">Go Back</a>
			</div>
		</div>
	</div>
</body>
</html>

django_blog/blogs/templates/blogs/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Blog site</title>
</head>
<body>
	<h1 style="text-align: center;">Blogs</h1>
	<div style="width: 70%;margin: 0px auto;">
		<hr />
		{% for blog in blogs %}
		<div>
			<h3>{{ blog.title }}</h3>
			{% if blog.image%}
			<div>
					<p><a href="{{ blog.image.url }}"><img alt="" src="{{ blog.image.large.url }}"/></a></p>
			</div>
			{% endif %}
			<div>{{ blog.text | truncatechars:100 }}</div>
			<div style="text-align: right;">
				<a href="{% url 'blogs:detail' blog_id=blog.id %}">Read</a>
			</div>
		</div>
		<hr />
		{% endfor %}
	</div>

{% if blogs.has_other_pages %}
  <ul class="pagination">
    {% if blogs.has_previous %}
      <li><a href="?page={{ blogs.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in blogs.paginator.page_range %}
      {% if blogs.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if blogs.has_next %}
      <li><a href="?page={{ blogs.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}


</body>
</html>